/**
 * Copyright 2014 Tomáš Ligenza
 *
 * This file is part of Firebird Visualization Tool.
 *
 * Firebird Visualization Tool is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * TinyUML is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Firebird Visualization Tool; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

package org.tinyuml.ui.diagram;

import java.awt.Dialog;
import org.tinyuml.model.ForeignKeyCol;
import org.tinyuml.model.Relation;
import org.tinyuml.model.UmlRelation;
import org.tinyuml.model.UmlTable;
import org.tinyuml.umldraw.eer.Relationship;
import org.tinyuml.util.ApplicationResources;

/**
 *
 * @author Tomáš Ligenza
 */
public class EditRelationshipDialog extends javax.swing.JDialog {

	private boolean isOk = false;
	
	private Relationship relationship;
	
	private UmlTable referencingTable;
	private UmlTable referencedTable;
	
	/**
	 * Creates new form EditRelationshipDialog
	 */
	public EditRelationshipDialog(java.awt.Window window, Relationship aRelationship) {
		
		super(window, Dialog.ModalityType.APPLICATION_MODAL);
		
		relationship = aRelationship;
		
		initComponents();
		
		myInit();
	}
	
	public void myInit() {
		
		referencingTable = (UmlTable) ((Relation) relationship.getModelElement()).getElement1();
		referencedTable = (UmlTable) ((Relation) relationship.getModelElement()).getElement2();
		
		referencingTableName.setText(referencingTable.getName());
		referencingTableForeignKey.setText(((UmlRelation) relationship.getRelation()).getForeignKey().getName());
		
		String keyNames = "";
		
		for(ForeignKeyCol col : ((UmlRelation) relationship.getRelation()).getForeignKey().getKeyCols()) {
			
			if(keyNames.equals(""))
				keyNames += "\n";
			
			keyNames += col.getName() + ": " + referencingTable.getColByName(col.getName()).getColType().name();
		}
		referencingTableCol.setText(keyNames);
		
		if(relationship.getRelation().isElement1Mandatory())
			referencingTableMandatoryCheckBox.setSelected(true);
		
		
		referencedTableName.setText(referencedTable.getName());
		
		String indexNames = "";
		
		for(ForeignKeyCol col : ((UmlRelation) relationship.getRelation()).getForeignKey().getReferencedCols()) {
			
			if(indexNames.equals(""))
				indexNames += "\n";
			
			indexNames += col.getName() + ": " + referencedTable.getColByName(col.getName()).getColType().name();
		}
		referencedTableCol.setText(indexNames);
		
		if(relationship.getRelation().isElement2Mandatory())
			referencedTableMandatoryCheckBox.setSelected(true);
		
		if(relationship.getRelation().isOneOnOne())
			oneToOneRadioButton.setSelected(true);
		else
			oneToManyRadioButton.setSelected(true);
		
		identifyingCheckBox.setSelected(relationship.getRelation().isIdentifying());
	}
	
	public boolean isReferencingTableMandatory() {
		
		return referencingTableMandatoryCheckBox.isSelected();
	}
	
	public boolean isReferencedTableMandatory() {
		
		return referencedTableMandatoryCheckBox.isSelected();
	}
	
	public boolean isOneToOne() {
		
		return oneToOneRadioButton.isSelected();
	}
	
	public boolean isOneToMany() {
		
		return oneToManyRadioButton.isSelected();
	}
	
	public boolean isIdentifying() {
		
		return identifyingCheckBox.isSelected();
	}
	
	public boolean isOk() { return isOk; }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        referencingPanel = new javax.swing.JPanel();
        referencingTableName = new javax.swing.JLabel();
        referencingTableForeignKeyLabel = new javax.swing.JLabel();
        referencingTableForeignKey = new javax.swing.JLabel();
        referencingTableColLabel = new javax.swing.JLabel();
        referencingTableCol = new javax.swing.JLabel();
        referencingTableMandatoryCheckBox = new javax.swing.JCheckBox();
        referencedPanel = new javax.swing.JPanel();
        referencedTableName = new javax.swing.JLabel();
        referencedTableColLabel = new javax.swing.JLabel();
        referencedTableCol = new javax.swing.JLabel();
        referencedTableMandatoryCheckBox = new javax.swing.JCheckBox();
        oneToManyRadioButton = new javax.swing.JRadioButton();
        oneToOneRadioButton = new javax.swing.JRadioButton();
        identifyingCheckBox = new javax.swing.JCheckBox();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        referencingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Referencing Table"));

        referencingTableName.setFont(new java.awt.Font("Ubuntu Mono", 1, 13)); // NOI18N
        referencingTableName.setText("jLabel1");

        referencingTableForeignKeyLabel.setText("Foreign Key:");

        referencingTableForeignKey.setText("jLabel1");

        referencingTableColLabel.setText("Cols:");

        referencingTableCol.setText("jLabel1");

        referencingTableMandatoryCheckBox.setText("Mandatory");

        javax.swing.GroupLayout referencingPanelLayout = new javax.swing.GroupLayout(referencingPanel);
        referencingPanel.setLayout(referencingPanelLayout);
        referencingPanelLayout.setHorizontalGroup(
            referencingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referencingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(referencingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(referencingTableName)
                    .addGroup(referencingPanelLayout.createSequentialGroup()
                        .addGroup(referencingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(referencingTableForeignKeyLabel)
                            .addComponent(referencingTableColLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(referencingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(referencingTableCol)
                            .addComponent(referencingTableForeignKey)))
                    .addComponent(referencingTableMandatoryCheckBox))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        referencingPanelLayout.setVerticalGroup(
            referencingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referencingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(referencingTableName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referencingTableForeignKeyLabel)
                    .addComponent(referencingTableForeignKey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referencingTableColLabel)
                    .addComponent(referencingTableCol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(referencingTableMandatoryCheckBox)
                .addContainerGap())
        );

        referencedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Referenced Table"));

        referencedTableName.setFont(new java.awt.Font("Ubuntu Mono", 1, 13)); // NOI18N
        referencedTableName.setText("jLabel1");

        referencedTableColLabel.setText("Cols:");

        referencedTableCol.setText("jLabel1");

        referencedTableMandatoryCheckBox.setText("Mandatory");

        javax.swing.GroupLayout referencedPanelLayout = new javax.swing.GroupLayout(referencedPanel);
        referencedPanel.setLayout(referencedPanelLayout);
        referencedPanelLayout.setHorizontalGroup(
            referencedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referencedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(referencedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(referencedTableName)
                    .addGroup(referencedPanelLayout.createSequentialGroup()
                        .addComponent(referencedTableColLabel)
                        .addGap(4, 4, 4)
                        .addComponent(referencedTableCol))
                    .addComponent(referencedTableMandatoryCheckBox))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        referencedPanelLayout.setVerticalGroup(
            referencedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(referencedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(referencedTableName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(referencedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referencedTableColLabel)
                    .addComponent(referencedTableCol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(referencedTableMandatoryCheckBox)
                .addContainerGap())
        );

        buttonGroup1.add(oneToManyRadioButton);
        oneToManyRadioButton.setText("One-To-Many (1:n)");

        buttonGroup1.add(oneToOneRadioButton);
        oneToOneRadioButton.setText("One-To-One (1:1)");

        identifyingCheckBox.setText("Identifying relation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(referencingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(referencedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oneToManyRadioButton)
                            .addComponent(oneToOneRadioButton)
                            .addComponent(identifyingCheckBox))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(referencingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referencedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oneToManyRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneToOneRadioButton)
                .addGap(18, 18, 18)
                .addComponent(identifyingCheckBox)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relationship", jPanel1);

        cancelButton.setText(ApplicationResources.getInstance().getString("stdcaption.cancel"));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText(ApplicationResources.getInstance().getString("stdcaption.ok"));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

		dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

		isOk = true;
		dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox identifyingCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton oneToManyRadioButton;
    private javax.swing.JRadioButton oneToOneRadioButton;
    private javax.swing.JPanel referencedPanel;
    private javax.swing.JLabel referencedTableCol;
    private javax.swing.JLabel referencedTableColLabel;
    private javax.swing.JCheckBox referencedTableMandatoryCheckBox;
    private javax.swing.JLabel referencedTableName;
    private javax.swing.JPanel referencingPanel;
    private javax.swing.JLabel referencingTableCol;
    private javax.swing.JLabel referencingTableColLabel;
    private javax.swing.JLabel referencingTableForeignKey;
    private javax.swing.JLabel referencingTableForeignKeyLabel;
    private javax.swing.JCheckBox referencingTableMandatoryCheckBox;
    private javax.swing.JLabel referencingTableName;
    // End of variables declaration//GEN-END:variables
}
