/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tinyuml.ui.diagram;

import java.awt.Dialog;
import org.tinyuml.model.UmlProcedure;
import org.tinyuml.umldraw.eer.ProcedureElement;
import org.tinyuml.util.ApplicationResources;

/**
 *
 * @author cml
 */
public class EditProcedureDialog extends javax.swing.JDialog {

	private ProcedureElement objProcedureElement;
	
	private boolean isOk;
	
	/**
	 * Creates new form EditViewDialog
	 */
	public EditProcedureDialog(java.awt.Window parent, ProcedureElement procedureElement) {
		
		super(parent, Dialog.ModalityType.APPLICATION_MODAL);
		
		objProcedureElement = procedureElement;
		
		initComponents();
		
		myInit();
	}
	
	public void myInit() {
		
		UmlProcedure umlProcedure = (UmlProcedure) objProcedureElement.getModelElement();
		
		procedureName.setText(umlProcedure.getName());
		sourceProcedure.setText(umlProcedure.getSource());
	}
	
	public String getName() {
		
		return procedureName.getText();
	}
	
	public String getSource() {
		
		return sourceProcedure.getText();
	}
	
	/**
	 * Returns true if ok was clicked.
	 * @return true if ok was clicked
	 */
	public boolean isOk() { return isOk; }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        procedureName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sourceProcedure = new javax.swing.JTextArea();
        cancelButtonProcedure = new javax.swing.JButton();
        okButtonProcedure = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Název");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        sourceProcedure.setColumns(20);
        sourceProcedure.setRows(5);
        jScrollPane1.setViewportView(sourceProcedure);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(procedureName)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(procedureName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Procedura", jPanel1);

        cancelButtonProcedure.setText(ApplicationResources.getInstance().getString("stdcaption.cancel"));
        cancelButtonProcedure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonProcedureActionPerformed(evt);
            }
        });

        okButtonProcedure.setText(ApplicationResources.getInstance().getString("stdcaption.ok"));
        okButtonProcedure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonProcedureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(okButtonProcedure)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButtonProcedure)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButtonProcedure)
                    .addComponent(okButtonProcedure))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonProcedureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonProcedureActionPerformed

		dispose();
    }//GEN-LAST:event_cancelButtonProcedureActionPerformed

    private void okButtonProcedureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonProcedureActionPerformed

		isOk = true;
		dispose();
    }//GEN-LAST:event_okButtonProcedureActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButtonProcedure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton okButtonProcedure;
    private javax.swing.JTextField procedureName;
    private javax.swing.JTextArea sourceProcedure;
    // End of variables declaration//GEN-END:variables
}
